name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Backend Code
      uses: actions/checkout@v2

    - name: Build Backend Docker Image
      run: |
        docker build -t myapp/backend .

    - name: Tag and Push Backend Docker Image to Docker Hub
      run: |
        docker tag myapp/backend:latest shawmeer2/backend:latest
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u shawmeer2 --password-stdin
        docker push shawmeer2/backend:latest

    - name: Deploy Backend Locally
      run: |
        docker pull shawmeer2/backend:latest
        docker stop backend || true
        docker rm backend || true
        docker run -d --name backend -p 3001:3001 shawmeer2/backend:latest
