name: Backend CI/CD

# Trigger on push and pull request events on the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Backend Code
      uses: actions/checkout@v2

    - name: Run Backend Tests
      run: |
        npm install
        npm test

    - name: Build Backend Docker image
      run: |
        docker build -t myapp/backend .

    - name: Tag and Push Backend Docker image to Docker Hub
      run: |
        docker tag myapp/backend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy Backend to Local Environment
      run: |
        ssh user@your-server 'docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest && docker run -d -p 3001:3001 ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest'
